version: '3'
services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gwasdb
    restart: always
    ports:
      - '5434:5432'
    network_mode: bridge

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
