version: '3'
services:

  postgres:
    image: tparkerd/gwas
    restart: always
    ports:
      - '5434:5432'
    network_mode: bridge
    container_name: gwas_database

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
